## Copyright (c) 2025 Rootstock Labs
## Copyright (c) 2025 Andres Tarrio <andres.tarrio@rootstocklabs.com>
## Perform a reproducible build of BitcoinJ Thin and upload the resulting 
## JAR and pom files to an S3 bucket, along with the md5sums list for the build

name: Build and Upload BitcoinJ Thin

on:
  push:
    tags:
      - 'bitcoinj-thin-*'

jobs:
  ## build the image and upload it to S3
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: bitcoinj-thin-cd
    steps:
    - name: Set version
      run: echo "VERSION=${GITHUB_REF#refs/tags/bitcoinj-thin-}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build --no-cache -t bitcoinj-thin:${VERSION} bitcoinj-thin/${VERSION} 

    - name: Run container and extract files
      run: |
        docker run --name bitcoinj-thin-container -d bitcoinj-thin:${VERSION} /bin/true
        docker cp bitcoinj-thin-container:/home/bitcoinj-thin/${{ github.ref_name }}.jar ./${{ github.ref_name }}.jar
        docker cp bitcoinj-thin-container:/home/bitcoinj-thin/pom.xml ./${{ github.ref_name }}.xml

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Upload to S3 bucket
      run: |
        aws s3 sync . s3://rsk-repository/co/rsk/bitcoinj/bitcoinj-thin/${VERSION} \
          --exclude "*" \
          --include "${{ github.ref_name }}.jar" \
          --include "${{ github.ref_name }}.xml" \

    - name: Stop and remove container
      run: |
        docker stop bitcoinj-thin-container
        docker rm bitcoinj-thin-container
